version: '2.17.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    mem_limit: 750m
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:8.0.33
    restart: always
    ports:
      - 33061:33061
    environment:
      - MYSQL_USER=amz
      - MYSQL_ROOT_PASSWORD=44238313aA#
      - MYSQL_DATABASE=test
    networks:
      - app-net

networks:
  app-net:
